name: 'Create GitHub Deployment'
description: 'Create Deployment'
author: 'qoomon'
branding:
  icon: play
  color: blue

inputs:
  token:
    description: 'A GitHub access token'
    required: true
    default: '${{ github.token }}'

  repository:
    description: 'The repository of the deployment'
    required: true
    default: '${{ github.repository }}'
  ref:
    description: 'The repository ref of the deployment'
    required: true
    default: '${{ github.ref }}'

  task:
    description: 'The task of the deployment'
    default: 'deploy'
  description:
    description: 'The description of the deployment'
  payload:
    description: 'The payload of the deployment'
  environment:
    description: 'The environment of the deployment'
  production-environment:
    description: 'Specifies if the given environment is specific to the deployment and will no longer exist at some point in the future. Default: `false`'
  transient-environment:
    description: 'Specifies if the given environment is one that end-users directly interact with. Default: `true` when `environment` is `production` and `false` otherwise.'

  # --- initial status ---
  state:
    description: The initial status of the deployment
    default: 'in_progress'
    required: true
  environment-url:
    description: 'The environment URL of the deployment'

  # --- post run ---
  auto-close:
    description: 'Enable auto-close for the deployment'
    default: 'true'
  '#job-status':
    description: 'DO NOT SET MANUALLY'
    default: '${{ job.status }}'

  # --- Workarounds for missing GitHub Actions context variables ---
  job-name:
    default: '${{ github.job }}'
  '#job-matrix':
    description: 'DO NOT SET MANUALLY'
    default: '${{ toJSON(matrix) }}'
  workflow-context:
    description: '<REUSABLE_WORKFLOW_JOB_NAME>, $ {{ toJSON(matrix) }}'

outputs:
  deployment-id:
    description: 'The deployment id'

runs:
  using: node20

  main: dist/main/index.js
  post: dist/post/index.js
