name: 'Create GitHub Deployment Status'
description: 'Create Deployment Status'
author: 'qoomon'
branding:
  icon: tag
  color: blue

inputs:
  token:
    description: 'A GitHub access token'
    required: true
    default: '${{ github.token }}'

  repository:
    description: 'The repository to target'
  deployment-id:
    description: 'The deployment id'

  state:
    description: |
      The status of the deployment
      Valid values are "error", "failure", "inactive", "in_progress", "queued", "pending", or "success"
  description:
    description: 'The description of the deployment status'
  environment:
    description: 'The environment of the deployment status'
  environment-url:
    description: 'The environment URL of the deployment status'

  # --- Workarounds for missing GitHub Actions context variables ---
  job-name:
    default: '${{ github.job }}'
  '#job-matrix':
    description: 'DO NOT SET MANUALLY'
    default: '${{ toJSON(matrix) }}'
  workflow-context:
    description: '<REUSABLE_WORKFLOW_JOB_NAME>, $ {{ toJSON(matrix) }}'

outputs:
  deployment-id:
    description: 'The deployment id'

runs:
  using: node20

  main: dist/main/index.js
